package pro.devstudio.mobile.util;

import android.content.Context;
import android.content.SharedPreferences;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

import pro.devstudio.mobile.model.Project;

/**
 * Saves/loads the project list and creates project directory scaffolding.
 */
public class ProjectManager {

    private static final String PREF_NAME    = "devstudio_projects";
    private static final String KEY_PROJECTS = "projects_json";
    private static final Gson   GSON         = new Gson();

    private final Context context;

    public ProjectManager(Context context) {
        this.context = context.getApplicationContext();
    }

    // ── Project list ────────────────────────────────────────────────────────

    public List<Project> loadProjects() {
        String json = prefs().getString(KEY_PROJECTS, "[]");
        Type type = new TypeToken<List<Project>>() {}.getType();
        List<Project> list = GSON.fromJson(json, type);
        return list != null ? list : new ArrayList<>();
    }

    public void saveProjects(List<Project> projects) {
        prefs().edit().putString(KEY_PROJECTS, GSON.toJson(projects)).apply();
    }

    public void addProject(Project p, List<Project> list) {
        list.add(0, p);
        saveProjects(list);
    }

    public void deleteProject(Project p, List<Project> list) {
        list.remove(p);
        saveProjects(list);
        FileUtils.deleteRecursive(projectDir(p));
    }

    public void touchProject(Project p, List<Project> list) {
        p.lastModified = System.currentTimeMillis();
        saveProjects(list);
    }

    // ── File system ────────────────────────────────────────────────────────

    public File projectDir(Project p) {
        return new File(context.getFilesDir(), "projects/" + p.dirName());
    }

    /**
     * Creates the project directory and starter files based on the chosen template.
     */
    public void scaffoldProject(Project p) throws IOException {
        File root = projectDir(p);
        File javaDir = new File(root, "app/src/main/java/" + p.packageName.replace('.', '/'));
        File resLayout = new File(root, "app/src/main/res/layout");
        File resValues = new File(root, "app/src/main/res/values");
        javaDir.mkdirs();
        resLayout.mkdirs();
        resValues.mkdirs();

        // Manifest
        FileUtils.writeFile(new File(root, "app/src/main/AndroidManifest.xml"),
                manifestXml(p));

        // Main activity
        FileUtils.writeFile(new File(javaDir, "MainActivity.java"),
                mainActivityJava(p));

        // Layout
        FileUtils.writeFile(new File(resLayout, "activity_main.xml"),
                templateLayout(p.template));

        // strings.xml
        FileUtils.writeFile(new File(resValues, "strings.xml"),
                "<resources>\n    <string name=\"app_name\">" + p.name + "</string>\n</resources>\n");

        // build.gradle (app)
        FileUtils.writeFile(new File(root, "app/build.gradle"), appGradle(p));

        // Root build.gradle
        FileUtils.writeFile(new File(root, "build.gradle"),
                "plugins {\n    id 'com.android.application' version '8.2.2' apply false\n}\n");

        // settings.gradle
        FileUtils.writeFile(new File(root, "settings.gradle"),
                "rootProject.name = \"" + p.name + "\"\ninclude ':app'\n");

        // .gitignore
        FileUtils.writeFile(new File(root, ".gitignore"), gitignore());

        // README with build instructions
        FileUtils.writeFile(new File(root, "README.md"), readme(p));

        // Gradle wrapper properties (so Android Studio / gradle wrapper can pick a distribution)
        FileUtils.writeFile(new File(root, "gradle/wrapper/gradle-wrapper.properties"), gradleWrapperProperties());

        // Minimal gradlew scripts (these call the wrapper; the wrapper jar may be generated by Android Studio)
        FileUtils.writeFile(new File(root, "gradlew"), gradlewScript());
        FileUtils.writeFile(new File(root, "gradlew.bat"), gradlewBat());
    }

    // ── Templates ─────────────────────────────────────────────────────────

    private String manifestXml(Project p) {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n" +
               "    <application\n" +
               "        android:allowBackup=\"true\"\n" +
               "        android:label=\"" + p.name + "\"\n" +
               "        android:theme=\"@style/Theme.AppCompat.Light.DarkActionBar\">\n" +
               "        <activity\n" +
               "            android:name=\"." + p.packageName + ".MainActivity\"\n" +
               "            android:exported=\"true\">\n" +
               "            <intent-filter>\n" +
               "                <action android:name=\"android.intent.action.MAIN\" />\n" +
               "                <category android:name=\"android.intent.category.LAUNCHER\" />\n" +
               "            </intent-filter>\n" +
               "        </activity>\n" +
               "    </application>\n" +
               "</manifest>\n";
    }

    private String mainActivityJava(Project p) {
        return "package " + p.packageName + ";\n\n" +
               "import androidx.appcompat.app.AppCompatActivity;\n" +
               "import android.os.Bundle;\n\n" +
               "public class MainActivity extends AppCompatActivity {\n\n" +
               "    @Override\n" +
               "    protected void onCreate(Bundle savedInstanceState) {\n" +
               "        super.onCreate(savedInstanceState);\n" +
               "        setContentView(R.layout.activity_main);\n" +
               "    }\n" +
               "}\n";
    }

    private String templateLayout(String template) {
        return switch (template) {
            case "login" -> loginLayout();
            case "basic" -> basicLayout();
            case "list"  -> listLayout();
            default      -> emptyLayout();
        };
    }

    private String emptyLayout() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<LinearLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
               "    android:layout_width=\"match_parent\"\n" +
               "    android:layout_height=\"match_parent\"\n" +
               "    android:gravity=\"center\"\n" +
               "    android:orientation=\"vertical\">\n\n" +
               "    <TextView\n" +
               "        android:layout_width=\"wrap_content\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:text=\"Hello, World!\"\n" +
               "        android:textSize=\"24sp\" />\n\n" +
               "</LinearLayout>\n";
    }

    private String loginLayout() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<LinearLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
               "    android:layout_width=\"match_parent\"\n" +
               "    android:layout_height=\"match_parent\"\n" +
               "    android:gravity=\"center\"\n" +
               "    android:orientation=\"vertical\"\n" +
               "    android:padding=\"24dp\">\n\n" +
               "    <TextView\n" +
               "        android:layout_width=\"wrap_content\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:text=\"Sign In\"\n" +
               "        android:textSize=\"32sp\"\n" +
               "        android:textStyle=\"bold\"\n" +
               "        android:layout_marginBottom=\"32dp\" />\n\n" +
               "    <EditText\n" +
               "        android:id=\"@+id/et_email\"\n" +
               "        android:layout_width=\"match_parent\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:hint=\"Email\"\n" +
               "        android:inputType=\"textEmailAddress\"\n" +
               "        android:layout_marginBottom=\"12dp\" />\n\n" +
               "    <EditText\n" +
               "        android:id=\"@+id/et_password\"\n" +
               "        android:layout_width=\"match_parent\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:hint=\"Password\"\n" +
               "        android:inputType=\"textPassword\"\n" +
               "        android:layout_marginBottom=\"24dp\" />\n\n" +
               "    <Button\n" +
               "        android:id=\"@+id/btn_login\"\n" +
               "        android:layout_width=\"match_parent\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:text=\"Sign In\" />\n\n" +
               "</LinearLayout>\n";
    }

    private String basicLayout() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<androidx.coordinatorlayout.widget.CoordinatorLayout\n" +
               "    xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
               "    xmlns:app=\"http://schemas.android.com/apk/res-auto\"\n" +
               "    android:layout_width=\"match_parent\"\n" +
               "    android:layout_height=\"match_parent\">\n\n" +
               "    <com.google.android.material.appbar.AppBarLayout\n" +
               "        android:layout_width=\"match_parent\"\n" +
               "        android:layout_height=\"wrap_content\">\n" +
               "        <com.google.android.material.appbar.MaterialToolbar\n" +
               "            android:layout_width=\"match_parent\"\n" +
               "            android:layout_height=\"?attr/actionBarSize\"\n" +
               "            app:title=\"My App\" />\n" +
               "    </com.google.android.material.appbar.AppBarLayout>\n\n" +
               "    <TextView\n" +
               "        android:layout_width=\"wrap_content\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:text=\"Hello!\"\n" +
               "        app:layout_behavior=\"@string/appbar_scrolling_view_behavior\" />\n\n" +
               "    <com.google.android.material.floatingactionbutton.FloatingActionButton\n" +
               "        android:layout_width=\"wrap_content\"\n" +
               "        android:layout_height=\"wrap_content\"\n" +
               "        android:layout_gravity=\"bottom|end\"\n" +
               "        android:layout_margin=\"16dp\"\n" +
               "        app:srcCompat=\"@android:drawable/ic_input_add\" />\n\n" +
               "</androidx.coordinatorlayout.widget.CoordinatorLayout>\n";
    }

    private String listLayout() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<LinearLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
               "    android:layout_width=\"match_parent\"\n" +
               "    android:layout_height=\"match_parent\"\n" +
               "    android:orientation=\"vertical\">\n\n" +
               "    <androidx.recyclerview.widget.RecyclerView\n" +
               "        android:id=\"@+id/recyclerView\"\n" +
               "        android:layout_width=\"match_parent\"\n" +
               "        android:layout_height=\"match_parent\"\n" +
               "        android:padding=\"8dp\" />\n\n" +
               "</LinearLayout>\n";
    }

    private String appGradle(Project p) {
        return "plugins {\n    id 'com.android.application'\n}\n\n" +
               "android {\n" +
               "    namespace '" + p.packageName + "'\n" +
               "    compileSdk 34\n\n" +
               "    defaultConfig {\n" +
               "        applicationId \"" + p.packageName + "\"\n" +
               "        minSdk 26\n" +
               "        targetSdk 34\n" +
               "        versionCode 1\n" +
               "        versionName \"1.0\"\n" +
               "    }\n" +
               "    compileOptions {\n" +
               "        sourceCompatibility JavaVersion.VERSION_17\n" +
               "        targetCompatibility JavaVersion.VERSION_17\n" +
               "    }\n" +
               "}\n\n" +
               "dependencies {\n" +
               "    implementation 'androidx.appcompat:appcompat:1.6.1'\n" +
               "    implementation 'com.google.android.material:material:1.11.0'\n" +
               "}\n";
    }

    private SharedPreferences prefs() {
        return context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
    }

    // ── Additional scaffold helpers ─────────────────────────────────────────

    private String readme(Project p) {
        return "# " + p.name + "\n\n" +
               "This is a small Android project scaffolded by DevStudio mobile IDE.\n\n" +
               "How to build:\n\n" +
               "1. Open the project in Android Studio (recommended). Android Studio will fetch Gradle and build tools and you can run the app.\n\n" +
               "2. Or build from command line: (requires Android SDK + commandline tools and Gradle)\n\n" +
               "   ```bash\n" +
               "   # generate gradle wrapper if missing\n" +
               "   gradle wrapper\n" +
               "   ./gradlew assembleDebug\n" +
               "   ```\n\n" +
               "Notes:\n" +
               "- The project includes basic app module with a single Activity.\n" +
               "- If you want to produce a signed release, configure signing in app/build.gradle or via Android Studio.\n";
    }

    private String gitignore() {
        return "/.gradle\n" +
               "/local.properties\n" +
               "/.idea\n" +
               "/build\n" +
               "/**/build\n" +
               "*.iml\n";
    }

    private String gradleWrapperProperties() {
        return "distributionBase=GRADLE_USER_HOME\n" +
               "distributionPath=wrapper/dists\n" +
               "zipStoreBase=GRADLE_USER_HOME\n" +
               "zipStorePath=wrapper/dists\n" +
               "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.4.1-all.zip\n";
    }

    private String gradlewScript() {
        return "#!/usr/bin/env sh\n" +
               "# Minimal gradlew script. The Gradle wrapper jar must be present under gradle/wrapper/gradle-wrapper.jar\n" +
               "# If missing, run 'gradle wrapper' on a machine with Gradle installed, or open the project in Android Studio.\n" +
               "DIRNAME=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n" +
               "java -jar \"$DIRNAME/gradle/wrapper/gradle-wrapper.jar\" "$@"\n";
    }

    private String gradlewBat() {
        return "@echo off\r\n" +
               "REM Minimal gradlew.bat stub. Requires gradle/wrapper/gradle-wrapper.jar\r\n" +
               "set DIRNAME=%~dp0\r\n" +
               "java -jar "%DIRNAME%gradle\\wrapper\\gradle-wrapper.jar" %*\r\n";
    }
}
